name: Quality assurance

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build check
      run: npm run build

    - name: Codestyle check (ESLint)
      run: npm run lint

    - name: Codestyle check (svelte-check)
      run: npm run check
